export enum StandardMaterialBindPoint {
    SAMPLER,
    FACTORS,
    BASE_COLOR,
    EMISSIVE,
    METALLIC = 4,
    ROUGHNESS = 4,
    NORMAL,
    OCCLUSION,
    CLEARCOAT,
    CLEARCOAT_ROUGHNESS,
    CLEARCOAT_NORMAL,
    SPECULAR,
    SPECULAR_COLOR,
    TRANSMISSION,
    PBR_SPECULAR = 13,
    PBR_GLOSSINESS = 13,
    DIFFUSE,
    ANISOTROPY
}

export enum RenderFlag {
    BASE_COLOR,
    EMISSIVE,
    OPACITY,
    OCCLUSION,
    NORMAL,
    METALLIC,
    ROUGHNESS,
    TRANSMISSION,
    SPECULAR,
    SPECULAR_COLOR,
    CLEARCOAT,
    CLEARCOAT_NORMAL,
    CLEARCOAT_ROUGHNESS,
    PBR_SPECULAR,
    PBR_GLOSSINESS,
    DIFFUSE,
    ANISOTROPY
}


export enum StandardMaterialFactorsStartPoint {
    BASE_COLOR = 0,
    EMISSIVE = 4,
    METALLIC = 7,
    ROUGHNESS = 8,
    NORMAL = 9,
    OCCLUSION = 10,
    SPECULAR = 11,
    SPECULAR_COLOR = 12,
    TRANSMISSION = 15,
    PBR_SPECULAR = 16,
    PBR_GLOSSINESS = 19,
    DIFFUSE = 20,
    CLEARCOAT = 21,
    CLEARCOAT_ROUGHNESS = 22,
    CLEARCOAT_NORMAL = 23,
    ANISOTROPY = 24
}

export enum PipelineShaderLocations {
    POSITION,
    UV,
    NORMAL,
    JOINTS,
    WEIGHTS,
    TANGENT
}

export enum GeometryBindingPoint {
    MODEL_MATRIX,
    NORMAL_MATRIX,
    SKIN
}